---
- hosts: mongodb5
  become: true
  remote_user: ansible
  vars:
    replica_set_name: rs1
  tasks:
    - name: "Install aptitude"
      apt:
        name: aptitude
        state: latest
        update_cache: true
    - name: "Import MongoDB public key"
      apt_key:
         url: "https://www.mongodb.org/static/pgp/server-5.0.asc"
         state: present
    - name: "Add MongoDB repository"
      apt_repository:
         filename: '/etc/apt/sources.list.d/mongodb-org-5.0.list'
         repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse"
         state: present
         update_cache: yes
    - name: "Install MongoDB"
      apt: 
         name: mongodb-org
         state: present
         update_cache: yes  
      notify:
        - start mongodb  
    - name: copy config file
      template: 
        src: mongod.conf
        dest: /etc/mongod.conf
      notify:
        - restart mongodb
  handlers:
    - name: start mongodb
      service: 
        name: mongod
        state: started
    - name: restart mongodb
      service: 
        name: mongod
        state: restarted









    - name: copy config file
      copy:
        src: mongod.tpl
        dest: /etc/mongod.conf
        owner: root
        group: root
        mode: 0644


    - name: create /etc/security/limits.d/mongodb.conf
      copy:
        src: security-mongodb.conf
        dest: /etc/security/limits.d/mongodb.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - restart mongodb

