---
- hosts: users
  become: true
  remote_user: ansible
  vars_files:
    - list.yml
  tasks:
    - name: Ensure group "devops" exists
      ansible.builtin.group:
        name: devops
        state: present
    - name: Ensure group "Developer" exists
      ansible.builtin.group:
        name: developer
        state: present
    - name: Give sudo access to devops user
      blockinfile:
        path: /etc/sudoers
        insertafter: "root    ALL=(ALL)       ALL"
        block: |
          # Gives sudo access to the devops group
          %devops        ALL=(ALL)       NOPASSWD: ALL
    - name: add users
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        shell: /bin/bash
        state: "{{ item.state }}"
        remove: "{{ item.remove }}"
      with_items: "{{ user_details }}"
    - name: Set authorized key
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        state: "{{ item.state }}"
        key: "{{ item.key }}"
      with_items: "{{ user_details }}"
      ignore_errors: true
